version: "3.4"

services:
  server:
    build:
      context: .
      target: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - $PWD:/app
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - db
    links:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pass
