version: 2
jobs:
  build:
    working_directory: ~/mozilla/glam
    docker:
      - image: circleci/python:3.8
        environment:
          DJANGO_CONFIGURATION: Test
          DATABASE_URL: postgresql://postgres:pass@postgres/test?sslmode=disable
      - image: circleci/postgres:11
        name: postgres
        environment:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            sudo pip install -U pip
            pip install -r requirements.txt
      - run:
          command: |
            pytest glam/
  frontend-tests:
    working_directory: ~/mozilla/glam
    docker:
      - image: circleci/node:11.5
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      # - run: npm run test # don't run this until design library is gone

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - frontend-tests:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
